apiVersion: v1
kind: Service
metadata:
  name: geomaps-frontend-service
spec:
  type: NodePort
  selector:
    app: geomaps-frontend-nginx
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 80
